version: '2.2'

services:
  sharelatex:
    image: sharelatex/sharelatex
    container_name: sharelatex
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8987:80"
    volumes:
      - /opt/overleaf/sharelatex_data:/var/lib/overleaf
    environment:
      OVERLEAF_APP_NAME: Overleaf Community Edition
      OVERLEAF_MONGO_URL: mongodb://mongo/sharelatex
      OVERLEAF_REDIS_HOST: redis
      REDIS_HOST: redis
      ENABLE_CONVERSIONS: 'true'
      EMAIL_CONFIRMATION_DISABLED: 'true'
      ENABLED_LINKED_FILE_TYPES: 'project_file,project_output_file'

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    command: --replSet overleaf
    volumes:
      - /opt/overleaf/mongo_data:/data/db
      - ./bin/shared/mongodb-init-replica-set.js:/docker-entrypoint-initdb.d/mongodb-init-replica-set.js
    environment:
      MONGO_INITDB_DATABASE: sharelatex
    extra_hosts:
      - "mongo:127.0.0.1"
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "localhost:27017/test", "--eval", "db.stats().ok"]
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis:6.2
    container_name: redis
    restart: always
    volumes:
      - /opt/overleaf/redis_data:/data
